# Generated by Django 5.0.6 on 2025-05-18 23:59

import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('participants', '0028_alter_tournamentinstitution_adjudicators_requested_and_more'),
        ('registration', '0001_initial'),
        ('tournaments', '0013_scheduleevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=50, verbose_name='URL key')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='created on')),
                ('for_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'participants'), ('model', 'speaker')), models.Q(('app_label', 'participants'), ('model', 'adjudicator')), models.Q(('app_label', 'participants'), ('model', 'team')), models.Q(('app_label', 'participants'), ('model', 'institution')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='for content type')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.institution', verbose_name='institution')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.team', verbose_name='team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=utils.models.UniqueConstraint(fields=('tournament', 'url_key'), name='registr_invitation_tournament__url_key_uniq'),
        ),
    ]
